# Hydra config.
hydra:
  run:
    dir: ../Data/${run_id}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ./
  job:
    config:
      override_dirname:
        kv_sep: "_"
        item_sep: "-"
        exclude_keys:
          - env_dir
          - env
          - seed
          - cuda
          - run_options
          - engine_config.width
          - engine_config.height
