behaviors:
  ChickAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2000
      buffer_size: 2048
      learning_rate: 0.003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.0
      rnd:
        gamma: 0.99
        strength: 1.0
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    checkpoint_interval: 50000
    keep_checkpoints: 22
    max_steps: 1.0e6
    time_horizon: 128
    summary_freq: 30000
